server:
  port: 8080
  servlet:
    session:
      timeout: 6000

  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain

spring:
  jackson:
    time-zone: GMT+8
  application:
    name: 工时管理系统
  profiles:
    active: #spring.profiles.active#
  datasource:
    url: jdbc:mysql://localhost:3306/project-management?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    locations: classpath:/db
    baseline-on-migrate: true
  liquibase:
    enabled: true
  redis:
    host: localhost
    port: 6379

mybatis:
  #  mapper文件
  mapper-locations: classpath:mapper/**/*.xml
  #  实体类
  type-aliases-package: com/nuist/projectManagement/domain
