server:
  port: 8080
  servlet:
    session:
      timeout: 6000

spring:
  application:
    name: 末端供应链
  profiles:
    active: #spring.profiles.active#
  datasource:
    url: jdbc:mysql://10.12.49.26:3306/end-supply-chain?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  liquibase:
    enabled: true
  redis:
    host: 10.12.49.26
    port: 6379
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true

  messages:
    basename: i18n/messages

application:
  upload:
    filePath: D:/data/upload/
    webPath: http://localhost:8080/upload
