server:
  port: 8080
  servlet:
    session:
      timeout: 6000

  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain

spring:
  jackson:
    time-zone: GMT+8
  application:
    name: 末端供应链
  profiles:
    active: #spring.profiles.active#
  datasource:
    url: jdbc:mysql://localhost:3306/end-supply-chain-0812?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    locations: classpath:/db
    baseline-on-migrate: true
  liquibase:
    enabled: true
  redis:
    host: localhost
    port: 6379
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true

  messages:
    basename: i18n/messages

application:
  upload:
    filePath: D:/data/upload/
    pathPatterns: /upload/**
    webPath: http://localhost:8080/upload

